Controllers/ContactoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Proyecto_Vesa.Data;
using Proyecto_Vesa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Proyecto_Vesa.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ProjectDbContext _db;
        public ContactoController(ProjectDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Contacto()
        {
            List<SelectListItem> listarTemas = new List<SelectListItem>();
            listarTemas.Add(new SelectListItem { Text = "Consulta", Value = "Consulta" });
            listarTemas.Add(new SelectListItem { Text = "Felicitación", Value = "Felicitación" });
            listarTemas.Add(new SelectListItem { Text = "Problema", Value = "Problema" });
            listarTemas.Add(new SelectListItem { Text = "Queja", Value = "Queja" });

            ViewBag.listaTemas = listarTemas;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Contacto(Contacto Contacto)
        {
            if (ModelState.IsValid)
            {
                _db.Contactos.Add(Contacto);
                await _db.SaveChangesAsync();

                TempData["Mensaje"] = "Mensaje enviado!";

                return RedirectToAction("Index", "Home");

            }
            return View();
        }
    }
}

Controllers/VentasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Proyecto_Vesa.Data;
using Proyecto_Vesa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using X.PagedList;

namespace Proyecto_Vesa.Controllers
{
    [Authorize]
    public class VentasController : Controller
    {
        private readonly ProjectDbContext _db;
        public VentasController(ProjectDbContext db)
        {
            _db = db;
        }
        // GET: VentasController
        public IActionResult Index(int? page = 1)
        {
            //Paginacion
            var pageNumber = page ?? 1;
            int pageSize = 10;

            //Listar Ventas
            ViewBag.Ventas = _db.Ventas.OrderBy(f=> f.Fecha).ToPagedList(pageNumber, pageSize);

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VESA - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/flexslider.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary text-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="~/Home">
                    <img src="~/img/logo_navbar.png" alt="..." height="40" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Destinos" asp-action="Index">Destinos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Destinos" asp-action="Promociones">Promociones</a>
                        </li>
                        <!--Llamar elementos de menu para usuarios con rol"Admin"-->
                        <partial name="_LoginAdminPartial.cshtml">
                            <!---->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Contacto">Contactenos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Nosotros">Nosotros</a>
                            </li>
                            <li class="nav-item">
                                <div class="d-flex d-inline rounded-lg h-75" id="cart">
                                    <a href="/destinos/carrito" class="btn btn-default" id="cartLogo">
                                        <i class="fa fa-shopping-cart"></i>
                                    </a>
                                    <p class="pr-2">Items:<span class="quantityCart pl-1 font-weight-bold">0</span></p>
                                </div>

                            </li>
                    </ul>
                    <partial name="_LoginPartial.cshtml">
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-primary">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-center textColor">
        <div class="container">
            &copy; 2022 - Proyecto_Vesa - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.flexslider.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&callback=initialize"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/moment/moment.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
<script type="text/javascript">
		// Mensajes de error
		var mensaje = '@TempData["Mensaje"]';
			if (mensaje != '')
				Swal.fire({
				  icon: 'success',
				  title: mensaje,
				  showConfirmButton: false,
				  timer: 1500
				})

		var mensajeError = '@TempData["Error"]';
		if (mensajeError != '')
			Swal.fire({
				icon: 'error',
				title: mensajeError,
				showConfirmButton: false,
				timer: 1500
            })

		var mensajeCarrito = '@TempData["Carrito"]';
        if (mensajeCarrito == 'Borrar Carrito')
        {
            localStorage.removeItem('listaCarritoDestinos');
        }
</script>

Views/Shared/_LoginAdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Proyecto_Vesa.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (SignInManager.IsSignedIn(User) && @UserManager.FindByNameAsync(UserManager.GetUserName(User)).Result.UserRole == "Admin")
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Index">Ventas</a>
    </li>
}